### ISSUE TITLE
istioctl create does not validate input parsed correctly

### ISSUE THREAD

**Issue by esnible** [istio/manager#281]
For example, if it is passed

```type: destination-policy
name: ratings-delay
spec:
  destination: ratings.default.svc.cluster.local
  tags:
    version: v1
  http_fault:
    headers:
      Cookie:
        regex: "^(.*?;)?(user=jason)(;.*)?$"
    delay:
      fixed_delay:
        percent: 100
        fixed_delay_seconds: 7.0
```

it does not complain but creates a _destination-policy_ will empty delay and Cookie.  If the YAML doesn't go into the protobuf the CLI should reject it with a message such as "cannot parse proto message: unknown field ..."

**Comment by frankbu** [comment]
I noticed that match does not work properly either:

Problem 1)

create:
```
type: route-rule
name: reviews-test-v2
spec:
  destination: reviews.default.svc.cluster.local
  precedence: 2
  match:
    httpHeaders:
      Cookie:
        regex: "^(.*?;)?(user=jason)(;.*)?$"
  route:
  - tags:
      version: v2
```
list:
```
kind: route-rule
name: reviews-test-v2
namespace: default
spec:
  destination: reviews.default.svc.cluster.local
  match: {}
  precedence: 2
  route:
  - tags:
      version: v2
```
Problem 2)

create:
```
type: route-rule
name: reviews-test-v2
spec:
  destination: reviews.default.svc.cluster.local
  precedence: 2
  match:
    http_headers:
      Cookie:
        regex: "^(.*?;)?(user=jason)(;.*)?$"
  route:
  - tags:
      version: v2
```
list:
```
kind: route-rule
name: reviews-test-v2
namespace: default
spec:
  destination: reviews.default.svc.cluster.local
  match:
    httpHeaders:
      Cookie: {}
  precedence: 2
  route:
  - tags:
      version: v2
```
