### ISSUE TITLE
Full validation needed for route-rules and destination-policies

### ISSUE THREAD

**Issue by esnible** [istio/manager#418]
Note that this is related to #406.  That Issue is about rules that have incorrect or no meaning given the current environment.  This issue is about rules that are just plain invalid.

Here are some things I have noticed
Non-ASCII hostnames can be created by istioctl

```
type: route-rule
name: xyz-rule
spec:
  destination: couchdb.€.svc.cluster.local
  http_fault:
    delay:
      percent: 100
      fixed_delay_seconds: 5
```

FQDNs with length > 255 octets can be created by istioctl

(same as above, with destination couchdb.123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890.svc.cluster.local )

HTTP fault / delay with percent > 100 is allowed.

HTTP fault / delay with fixed_delay_seconds < 0 is allowed
